### ISSUE TITLE
absolutely agree with you

### ISSUE THREAD

**Issue by hello2dj** [StarpTech/dart-nodejs#1]
"if you don't rely heavily on other javascript libraries use Dart it will boost your productivity to Over 5000"

npm has so many libraries, but pub is too weak.

**Comment by StarpTech** [comment]
Hi @hello2dj that's correct the ecosystem is really young but the developer tools and the language features are worth to remain. Dart need more community work. 

Here is the full version of my statement.

> If you don't use Node.Js for isomorphic applications and if you don't rely heavily on other javascript libraries use Dart it will boost your productivity to Over 5000. You can still apply many concepts from Node.Js like Classes (ES6), Mixed Inheritance, Event Loop characteristics, Promises (Futures), Async/Await, try/catch, Streams, lexical scoping. closures...

**Comment by hello2dj** [comment]
yes Dart need another TJ or Matteo Collina or you and every one like it。i like it cause simple and typed etc.

**Comment by StarpTech** [comment]
@hello2dj thanks for the nice words 😄
